services:
  discord-music-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-music-bot
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TOKEN=${TOKEN}
      - PREFIX=${PREFIX:-/}
      - PIPE_MODE_MAX_TIME=${PIPE_MODE_MAX_TIME:-10}
      - STORAGE_PATH=/app/storage
      - GLOBAL_AGENT_ENVIRONMENT_VARIABLE_NAMESPACE=
      - HTTP_PROXY=${HTTP_PROXY:-http://host.docker.internal:2080}
      - HTTPS_PROXY=${HTTPS_PROXY:-http://host.docker.internal:2080}
      - http_proxy=${HTTP_PROXY:-http://host.docker.internal:2080}
      - https_proxy=${HTTPS_PROXY:-http://host.docker.internal:2080}
      - ALL_PROXY=${ALL_PROXY:-http://host.docker.internal:2080}
      - NO_PROXY=${NO_PROXY:-localhost,127.0.0.1}
      - no_proxy=${NO_PROXY:-localhost,127.0.0.1}
    volumes:
      - ./storage:/app/storage
    # ports:
    #   - "3004:80"
